name: Update GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *' # รันทุกเที่ยงคืน (เวลา Server)
  workflow_dispatch: # ปุ่มกดรันเองได้

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Stats Image
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          card: stats
          # ตรงนี้ใส่ options เหมือนที่เคยใส่ใน URL ได้เลย
          options: 'username=nattapat2871&show_icons=true&theme=radical' 
          path: 'generated/stats.svg' # ไฟล์จะถูกสร้างที่โฟลเดอร์นี้

      - name: Generate Top Langs Image
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          card: top-langs
          options: 'username=nattapat2871&layout=compact&theme=radical'
          path: 'generated/top-langs.svg'

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated/
          git commit -m "Update stats" || exit 0
          git push
